<#
.SYNOPSIS
  Register (or remove) a Windows scheduled task that runs Intern Radar locally.

.DESCRIPTION
  Polls every 5 minutes while this PC is on. Safe to run alongside the GitHub
  Actions workflow - the seen-postings store keeps alerts firing exactly once,
  whichever runner gets there first.

.EXAMPLE
  .\run_local.ps1 -WebhookUrl "https://discord.com/api/webhooks/..."
  .\run_local.ps1 -Remove
#>
[CmdletBinding()]
param(
    [string]$WebhookUrl,
    [int]$IntervalMinutes = 5,
    [switch]$Remove
)

$ErrorActionPreference = 'Stop'
$TaskName = 'InternRadar'
$Root     = $PSScriptRoot

if ($Remove) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Removed scheduled task '$TaskName'." -ForegroundColor Green
    } else {
        Write-Host "No scheduled task named '$TaskName' found."
    }
    return
}

if (-not $WebhookUrl) {
    throw "Pass -WebhookUrl, or use -Remove to uninstall. See README step 1."
}
if ($WebhookUrl -notmatch '^https://discord(app)?\.com/api/webhooks/') {
    throw "That does not look like a Discord webhook URL."
}

$python = (Get-Command python -ErrorAction SilentlyContinue).Source
if (-not $python) { throw "python was not found on PATH." }

# The webhook is written to a local launcher rather than baked into the task
# definition, so it never shows up in Task Scheduler's UI or exported XML.
$launcher = Join-Path $Root 'run_once.ps1'
@"
# Generated by run_local.ps1 - contains a secret, do not commit.
`$env:DISCORD_WEBHOOK_URL = '$WebhookUrl'
Set-Location '$Root'
& '$python' -m intern_radar.main *>> '$Root\radar.log'
"@ | Set-Content -Path $launcher -Encoding utf8

# Keep the secret out of git.
$gitignore = Join-Path $Root '.gitignore'
foreach ($entry in @('run_once.ps1', 'radar.log')) {
    if (-not (Select-String -Path $gitignore -Pattern "^$([regex]::Escape($entry))$" -Quiet -ErrorAction SilentlyContinue)) {
        Add-Content -Path $gitignore -Value $entry -Encoding utf8
    }
}

$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$launcher`""

$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Description 'Poll hardware internship boards and alert on Discord' | Out-Null

Write-Host "Registered '$TaskName' - runs every $IntervalMinutes minutes." -ForegroundColor Green
Write-Host "  Log:     $Root\radar.log"
Write-Host "  Run now: Start-ScheduledTask -TaskName $TaskName"
Write-Host "  Remove:  .\run_local.ps1 -Remove"
